### ISSUE TITLE
Page background flashes black each time new tab is opened

### ISSUE THREAD

**Issue by silverwings15** [sajadhsm/new-word-tab#14] opened 2022-01-13 18:15 UTC
Hi, would it be possible to removing this black flash each time a new tab is opened?

![image](https://user-images.githubusercontent.com/10742312/149386087-603edb3f-76d4-434c-ae71-12e1ecf12cc3.png)

Thank you for this otherwise very innovative addon! Really looking forward to being able to import my own word lists in future updates

edit: i would also love to be able to have an ignore function/list in addition to learned, and being able to go back and edit both these lists

**Comment by silverwings15** [comment] 2022-01-14 09:47
> [flash of inaccurate color theme](https://css-tricks.com/flash-of-inaccurate-color-theme-fart/)

haha what an acronym

I was thinking of the ignored list as a way to remove words from the list entirely, but more flexible as it gives you the ability to go back and review them later. However, given what you say about the storage restriction, I'd be happy with just the ability to  remove words from the list without spamming up the learned list.

Also, you probably already know this, but some of the words in the current lists do not return a definition, however I'm aware this is a limitation of the free API that the addon uses. Being able to provide our own definitions for such words might be a solution, but probably doesn't seem feasible given the storage limit you mentioned. Would like to hear your thoughts on that

**Comment by sajadhsm** [comment] 2022-01-14 10:55
Now I see your point. The problem is that the words list is stored in the source code itself so it's not possible for the user to remove them without consuming additional storage.

The behavior of the ignored list is very similar to the learned list. We need to come up with a solution to minimize duplication and keep it as simple as possible.

---

One solution for the second problem is that we gradually add our own definitions in the source code so not only it's available to other users too but also it doesn't require additional storage. But it's hard to maintain, increase the bundle size, and requires a new release each time the definitions are updated. (If we somehow keep the definitions out of the source code, the later problem is avoidable)

Another solution would be finding other dictionary APIs to be used as fallbacks. But there is a chance that they don't give a definition as well.

One more solution is to contribute to Google Translate since the Free Dictionary API uses that as the source of the definitions. I don't know how to do that but it probably takes some time to be approved and published.

I'll try to see if I can find any other APIs or not. Meanwhile, it may be a good idea to have an issue to gather some missing definitions to get a better sense of the first approach. It would be awesome if you create that issue and maintain it for a while if you have the time :D

**Comment by silverwings15** [comment] 2022-01-14 11:14
> The behavior of the ignored list is very similar to the learned list. We need to come up with a solution to minimize duplication and keep it as simple as possible.

Could it be possible to keep them in the learned list, but color code them differently, and give them different attributes that make it possible to filter them from each other later

> One solution for the second problem is that we gradually add our own definitions in the source code so not only it's available to other users too but also it doesn't require additional storage. But it's hard to maintain, increase the bundle size, and requires a new release each time the definitions are updated. (If we somehow keep the definitions out of the source code, the later problem is avoidable)

Yes, it would definitely be too much effort to do so manually, not to mention possible disagreements about what sources to use.

> Another solution would be finding other dictionary APIs to be used as fallbacks. But there is a chance that they don't give a definition as well.

Also an issue, as i don't think there are many free dictionary APIs around to begin with. 

> One more solution is to contribute to Google Translate since the Free Dictionary API uses that as the source of the definitions. I don't know how to do that but it probably takes some time to be approved and published.

I've never heard of this 

> Meanwhile, it may be a good idea to have an issue to gather some missing definitions to get a better sense of the first approach. It would be awesome if you create that issue and maintain it for a while if you have the time :D

I will get started right away 😃

**Comment by sajadhsm** [comment] 2022-01-14 12:21
> Could it be possible to keep them in the learned list, but color code them differently, and give them different attributes that make it possible to filter them from each other later

Good idea. I just added [it](https://github.com/sajadhsm/new-word-tab/projects/1#card-76083692) to the road map.

> I will get started right away 😃

Awesome. Thanks for your feedback and participation. :raised_hands:

**Comment by sajadhsm** [comment] 2022-01-14 14:19
I changed the theme initialization logic. For debugging I used red and blue for the background color. It looks like the issue is fixed on Chrome but Firefox always has a black or white flash (base on system color schema) on new tabs.

I don't know if there is a way to override that or not.

Can you check out this debug build to see its behavior on your browser?

[ntw-flash-fix-experiment.zip](https://github.com/sajadhsm/new-word-tab/files/7870817/ntw-flash-fix-experiment.zip)

**Comment by silverwings15** [comment] 2022-01-14 14:42
i tried replacing the files in the .xpi with the ones you provided, but when i try to install that, it says file is corrupted. can you please send a signed .xpi instead?

**Comment by sajadhsm** [comment] 2022-01-14 14:58
First, you need to extract the zip file. Then:

**On Firefox:**
1. Open `about:debugging#/runtime/this-firefox`
2. Load temporary Add-on...
3. Select manifest.json

**On chrome:**
1. Open `chrome://extensions/`
2. Enable developer mode
3. Upload unpacked
4. Select the extension extracted folder

**Comment by silverwings15** [comment] 2022-01-14 15:06
very cool, TIL. this is what i see with the temporary extension

![image](https://user-images.githubusercontent.com/10742312/149537507-b088327c-77c1-486b-abb5-145c05a16422.png)

**Comment by sajadhsm** [comment] 2022-01-14 15:20
Do you still see a black/white or red flash when opening new tabs?

You can also try this one. (Without Blue and Red colors)
[nwt.zip](https://github.com/sajadhsm/new-word-tab/files/7871330/nwt.zip)

**Comment by silverwings15** [comment] 2022-01-14 15:29
Oh yes, silly me missing the point of the test.. There is still flashing on Firefox, but it uses some sort of white ish color derived from my theme or OS setting, so it's no issue at all. No flashing on Chrome at all 😁

**Comment by silverwings15** [comment] 2022-01-14 15:44
Glad to contribute what little I can, you deserve all the props for coming up with this ingenious extension ❤️

**Closed** 2022-01-14 17:30 UTC

**Comment by sajadhsm** [comment] 2022-01-14 17:54
@silverwings15 Hooray, it got approved really quickly both on Chrome and Firefox. You can update to `v1.3.1` ^_^

**Comment by silverwings15** [comment] 2022-01-14 18:03
amazing, must be some kind of record :^)

**Comment by silverwings15** [comment] 2022-05-11 05:48
hey, i just updated to 1.5.0 and it seems this issue is back D:

**Comment by sajadhsm** [comment] 2022-05-12 08:41
Oh no :(
Along the update, I moved the theme initialization logic to a separate script file to get rid of the CSP hash to prepare to migrate to manifest version 3.

I've tested it in Chrome and didn't notice any difference but in Firefox the default browser flash still applies.

Maybe need to find another approach. I'll take a look at it on the weekend.

**Comment by sajadhsm** [comment] 2022-05-13 13:24
Hey @silverwings15 

Just did some changes which I think fixes the bug. Could you please test it locally to confirm if the issue is gone?

[NWT_1.6.0-beta.zip](https://github.com/sajadhsm/new-word-tab/files/8688179/NWT_1.6.0-beta.zip)

Also, this version includes a **Background Option** that allows the user to set a custom background image for the pages. Your feedback on this new feature will be helpful too :D

**Comment by silverwings15** [comment] 2022-05-13 21:41
hmm, the flash is still there but very brief and only appears sometimes. i uploaded a video to help you visualize more easily 

https://user-images.githubusercontent.com/10742312/168392868-84fc4dfe-e9a9-491c-8c70-672df90dc002.mp4

 background image option is awesome and works as intended!

**Comment by sajadhsm** [comment] 2022-05-16 07:27
Thanks for the video and the feedback!

I've also tested it with red and blue colors to make it easier to detect the white/black flash.
[NWT_1.6.0_DEBUG.zip](https://github.com/sajadhsm/new-word-tab/files/8697965/NWT_1.6.0_DEBUG.zip)


On Chrome, there is no flash. But Firefox always has a flash base on the OS theme color, exactly like before (https://github.com/sajadhsm/new-word-tab/issues/14#issuecomment-1013224474).

I don't think there is much more we can do about it for now. :(

**Comment by silverwings15** [comment] 2022-05-16 09:13
blue = white and red = black right? i'm still getting very brief red flashes, same as with the black flashes in the video above.

https://user-images.githubusercontent.com/10742312/168559494-d82bfc09-ade1-4b5e-b7c9-a33e9e0539d2.mp4

**Comment by sajadhsm** [comment] 2022-05-16 09:40
Right.
Can you also test it on Chrome? It would be really helpful if you test it in a sandbox Firefox window too. There is a chance that your other extensions slow the overall execution.

Previously the fix script was written inlined in the HTML code so it loaded faster and the flash has less time to appear.
But since eventually, all extensions should migrate to the manifest version 3 and inline scripts will no longer be allowed, the implementation must go to a separated JS file and be imported into the HTML file which is a little slower.

Although it's very brief, it doesn't give a good feeling. It's better to be fixed.
I will give it one more shot and try to reproduce it on my PC. However, it may not get faster than this.

**Comment by silverwings15** [comment] 2022-05-16 09:57
i tested it on both Chrome and a new Firefox profile and you were right. there is no flashing at all on Chrome, and the red flash only appeared once on the fresh FF profile when i was opening a ton of tabs really quickly. so i guess my current FF profile has accumulated a lot of gunk that impacts performance. either way don't sweat about looking for further improvements though, this is already fantastic and i can always use NWT in Chrome or make a new FF profile if needed

**Comment by sajadhsm** [comment] 2022-05-16 10:11
Great, thank you so much.
I will release a new version this week including the background option and the flashing fix. ✌️ 

Have a wonderful rest of the day :D
